# Generated by Django 6.0.4 on 2026-04-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usermodel_email_alter_usermodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='account_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
