# Generated by Django 6.0.4 on 2026-04-29 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usermodel_account_status_usermodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
