# Generated by Django 6.0.4 on 2026-04-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usermodel_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
