# Generated by Django 6.0.4 on 2026-04-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobmodel_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobmodel',
            index=models.Index(fields=['job_type'], name='jobs_jobmod_job_typ_94ff2b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobmodel',
            index=models.Index(fields=['experience_level'], name='jobs_jobmod_experie_860a96_idx'),
        ),
        migrations.AddIndex(
            model_name='jobmodel',
            index=models.Index(fields=['is_active'], name='jobs_jobmod_is_acti_56fa53_idx'),
        ),
    ]
