# Generated by Django 6.0.4 on 2026-04-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='jobs.tag'),
        ),
    ]
