# Generated by Django 6.0.4 on 2026-05-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
