# Generated by Django 6.0.4 on 2026-05-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='uploads/resumes/'),
        ),
    ]
